on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

jobs:
  deploy_tf_ec2:
    name: "deploy_tf_ec2 :rocket:"
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        run: |
          terraform init

