# Triggers
on:
  push:
    branches:
      - 'main'

# Manage of OS to execute
defaults:
  run:
    shell: bash

# Organizing steps
jobs:
  deploy_tf_ec2:
    name: "deploy_tf_ec2 :rocket:"
    runs-on: "ubuntu-latest"

    # Manage of ENV variables as INPUTs
    env:
      AWS_ACCES_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        run: |
          terraform init

      - name: validate
        run: |
          terraform fmt
          terraform validate

      - name: plan
        run: |
          echo $AWS_ACCES_KEY_ID
          terraform plan

